language: rust
cache: cargo
os:
 - windows

script:
  - cargo build --release --all

deploy:
  skip_cleanup: true
  provider: releases
  token: $GH_TOKEN
  file: "target\\release\\charon.exe"
  on:
    tags: true
